### ISSUE TITLE
So many mismatches between data files and dataloader.py

### ISSUE THREAD

**Issue by haibin-chen** [lingyongyan/BootstrapGAN#1]
In def _load_file function of dataloader.py, I can't find entity_labels.txt, 'e_feature_'+feature_type+'.txt', 'pattern_labels.txt', 'pattern_label_vocab.txt', 'p_feature_'+feature_type+'.txt', 'links.txt'...

**Comment by lingyongyan** [comment]
Some files are renamed comparing to the datasets used in bootstrapping. I have uploaded a new dataset version.
